\contentsline {figure}{\numberline {1}{\ignorespaces The ECP Work Breakdown Structure through Level 3 (L3).\relax }}{3}{figure.caption.2}
\contentsline {figure}{\numberline {2}{\ignorespaces The xSDK is the first SDK for ECP ST, in the Mathematical Libraries technical area\nobreakspace {}\ref {table:wbs}. The xSDK provides the collaboration environment for improving build, install and testing capabilities for member packages such as hypre, PETSc, SuperLU and Trilinos (and other products with green background). Domain components (see orange ovals) are also an important category of the ecosystem, providing leveraged investments for common components in a specific scientific software domain. xSDK capabilities are essential for supporting the multi-physics and multi-scale application requirement that lead to combined use of xSDK libraries. Furthermore, the availability of advanced software platforms such as GitHub, Confluence, JIRA and others enable the level of collaboration needed to create an SDK from independently developed packages.\relax }}{6}{figure.caption.4}
\contentsline {figure}{\numberline {3}{\ignorespaces \textbf {xSDK Community Policies emerged from challenging and passionate discussions about essential values of the math libraries community.} Once established, these community policies represent a living statement of what it means to be part of an SDK, and are used as the criteria for welcoming future members.\relax }}{7}{figure.caption.5}
\contentsline {figure}{\numberline {4}{\ignorespaces \textbf {The ECP ST software stack is delivered to the user community through several channels.} Key channels are via source code, increasing using SDKs, direct to Facilities in collaboration with ECP HI, via binary distributions, in particular the OpenHPC project and via HPC vendors. The SDK leadership team includes ECP ST team members with decades of experience delivering scientific software products.\relax }}{9}{figure.caption.6}
\contentsline {figure}{\numberline {5}{\ignorespaces Project remapping summary from Phase 1 (through November 2017) to Phase 2 (After November 2017)\relax }}{9}{figure.caption.8}
\contentsline {figure}{\numberline {6}{\ignorespaces ECP ST before November 2017 reorganization. This conceptually layout emerged from several years of Exascale planning, conducted primarily within the DOE Office of Advanced Scientific Computing Research (ASCR). After a significant restructuring of ECP that removed much of the facilities activities and reduced the project timeline from 10 to seven years, and a growing awareness of what risks had diminished, this diagram no longer represented ECP ST efforts accurately.\relax }}{11}{figure.caption.9}
\contentsline {figure}{\numberline {7}{\ignorespaces ECP ST after November 2017 reorganization. This diagram more accurately reflects the priorities and efforts of ECP ST given the new ECP project scope and the demands that we foresee.\relax }}{11}{figure.caption.10}
\contentsline {figure}{\numberline {8}{\ignorespaces ECP ST Leadership Team as of November 2017.\relax }}{12}{figure.caption.11}
\contentsline {figure}{\numberline {9}{\ignorespaces {\relax \fontsize {9}{11}\selectfont \abovedisplayskip 8.5\p@ plus3\p@ minus4\p@ \abovedisplayshortskip \z@ plus2\p@ \belowdisplayshortskip 4\p@ plus2\p@ minus2\p@ \def \leftmargin \leftmargini \parsep 4\p@ plus2\p@ minus\p@ \topsep 8\p@ plus2\p@ minus4\p@ \itemsep 4\p@ plus2\p@ minus\p@ {\leftmargin \leftmargini \topsep 4\p@ plus2\p@ minus2\p@ \parsep 2\p@ plus\p@ minus\p@ \itemsep \parsep }\belowdisplayskip \abovedisplayskip {The 54 ECP ST Projects contribute to 89 unique products. ECP ST products are delivered to users via many mechanisms. Provides experience we can leverage across projects. Building via Spack is required for participating in ECP ST releases: 48\% of products already support Spack. 24\% have Spack support in progress. Use of Spack and the ECP ST SDKs will greatly improve builds from source. 81 of 89 packages support users via source builds.}}\relax }}{25}{figure.caption.13}
\contentsline {figure}{\numberline {10}{\ignorespaces ECP ST staff are involved in a variety of official and \textit {de facto} standards committees. Involvement in standards efforts is essential to assuring the sustainability of our products and to assure that emerging Exascale requirements are addressed by these standards.\relax }}{30}{figure.caption.19}
\contentsline {figure}{\numberline {11}{\ignorespaces \textbf {New Legion features such as dynamic tracing significantly improves strong scaling in unstructured mesh computations.}\relax }}{35}{figure.caption.21}
\contentsline {figure}{\numberline {12}{\ignorespaces \textbf {Work by ROSE team shows performance gap analysis for RAJA with different compilers.}\relax }}{37}{figure.caption.22}
\contentsline {figure}{\numberline {13}{\ignorespaces Kokkos Execution and Memory Abstractions\relax }}{38}{figure.caption.23}
\contentsline {figure}{\numberline {14}{\ignorespaces DARMA software stack model showing application-level code implemented with asynchronous programming model (DARMA header library). Application-level semantics are translated into a task graph specification via metaprogramming in the translation layer. Glue code maps task graph specification to individual runtime libraries. Current backend implementations include std::threads, Charm++, MPI + OpenMP, and HPX.\relax }}{41}{figure.caption.24}
\contentsline {figure}{\numberline {15}{\ignorespaces Improved performance of strided get in the 5.7 release series.\relax }}{43}{figure.caption.25}
\contentsline {figure}{\numberline {16}{\ignorespaces MPICH milestones completed in June 2018 and Septmeber 2018\relax }}{47}{figure.caption.26}
\contentsline {figure}{\numberline {17}{\ignorespaces PaRSEC architecture\relax }}{50}{figure.caption.27}
\contentsline {figure}{\numberline {18}{\ignorespaces Strong-scaling performance of the ABCD term in the coupled-cluster doubles equation for $(H_2O)_{12}$ in aug-cc-pVDZ basis set.\relax }}{51}{figure.caption.28}
\contentsline {figure}{\numberline {19}{\ignorespaces Comparison of DPLASMA and SLATE Cholesky factorization over PaRSEC with SLATE and ScaLAPACK on 64 nodes 12 cores each\relax }}{51}{figure.caption.29}
\contentsline {figure}{\numberline {20}{\ignorespaces Envisioned PowerStack\relax }}{57}{figure.caption.30}
\contentsline {figure}{\numberline {21}{\ignorespaces SOLLVE thrust area updates\relax }}{59}{figure.caption.31}
\contentsline {figure}{\numberline {22}{\ignorespaces Argobots execution model\relax }}{61}{figure.caption.32}
\contentsline {figure}{\numberline {23}{\ignorespaces Pictorial representation of development of BOLT\relax }}{63}{figure.caption.33}
\contentsline {figure}{\numberline {24}{\ignorespaces Weak scaling of distributed hash table insertion on the KNL partition of NERSC's Cori platform. The dotted line represents the processes in one node.\vspace {-.4cm}\relax }}{65}{figure.caption.34}
\contentsline {figure}{\numberline {25}{\ignorespaces Selected GASNet-EX vs. MPI RMA Performance Results\relax }}{67}{figure.caption.35}
\contentsline {subfigure}{\numberline {(a)}{\ignorespaces {8-byte RMA Latencies}}}{67}{subfigure.25.1}
\contentsline {subfigure}{\numberline {(b)}{\ignorespaces {Aries Flood Bandwidth}}}{67}{subfigure.25.2}
\contentsline {figure}{\numberline {26}{\ignorespaces This graph shows the performance of Qthreads and OpenMP paired with the FinePoints library for multithreaded MPI. The x-axis varies the buffer sizes transferred in each experiment in the series, and the y-axis shows the network bandwidth achieved. The similar performance of Qthreads and OpenMP justifies use of the former as a suitable proxy for the latter, with the advantage of flexibility for rapid prototyping of new runtime system techniques.\relax }}{69}{figure.caption.36}
\contentsline {figure}{\numberline {27}{\ignorespaces Interface for complex memory that is abstract, portable, extensible to future hardware; including a mechanism-based low-level interface that reins in heterogeneity and an intent-based high-level interface that makes reasonable decisions for applications\relax }}{70}{figure.caption.37}
\contentsline {figure}{\numberline {28}{\ignorespaces Compile time improvements and object file size reductions for Kokkos applications with an increasing number of parallel-for looping constructs.\relax }}{76}{figure.caption.38}
\contentsline {figure}{\numberline {29}{\ignorespaces Approach to processing user application code with multiple tools to support optimization and correctness checking.\relax }}{81}{figure.caption.39}
\contentsline {figure}{\numberline {30}{\ignorespaces (a) PAPI SDE-Recorder logging convergence of different ILU-preconditioned MAGMA-sparse Krylov solvers for a 2D/3D Problem; (b) PAPI SDE-Recorder logging the status of different task queues in PaRSEC.\relax }}{84}{figure.caption.40}
\contentsline {subfigure}{\numberline {(a)}{\ignorespaces { }}}{84}{subfigure.30.1}
\contentsline {subfigure}{\numberline {(b)}{\ignorespaces { }}}{84}{subfigure.30.2}
\contentsline {figure}{\numberline {31}{\ignorespaces Y-TUNE Solution Approach.\relax }}{86}{figure.caption.41}
\contentsline {figure}{\numberline {32}{\ignorespaces (a) HPCToolkit's {\tt hpcviewer} showing a detailed attribution of GPU performance metrics in a profile of an optimized, GPU-accelerated benchmark written in OpenMP\nobreakspace {}5.0. (b) HPCToolkit's {\tt hpctraceviewer} showing an execution trace of DCA+ --- a quantum Monte Carlo code that creates many short-lived threads as it simulates correlated electron systems in high temperature superconductors.\relax }}{88}{figure.caption.42}
\contentsline {figure}{\numberline {33}{\ignorespaces TAU's ParaProf profile browser shows the parallel performance of the CANDLE application, where half the threads are engaged in one activity (\texttt {pthread\_cond\_wait}) while the other half is engaged in some other activity (\texttt {Eigen::internal::gebp\_kernel}). \relax }}{92}{figure.caption.43}
\contentsline {figure}{\numberline {34}{\ignorespaces Using PapyrusKV for Meraculous.\relax }}{94}{figure.caption.44}
\contentsline {subfigure}{\numberline {(a)}{\ignorespaces {K-mer distributed hash table implementations in UPC and PapyrusKV.}}}{94}{subfigure.34.1}
\contentsline {subfigure}{\numberline {(b)}{\ignorespaces {Meraculous performance comparison between PapyrusKV (PKV) and UPC on Cori.}}}{94}{subfigure.34.2}
\contentsline {figure}{\numberline {35}{\ignorespaces The December 2017 release of the xSDK contains many of the most popular math and scientific libraries used in HPC. The above diagram shows the interoperability of the libraries and a multiphysics or multiscale application.\relax }}{99}{figure.caption.45}
\contentsline {figure}{\numberline {36}{\ignorespaces Performance of new GMRES on Vulcan at LLNL\relax }}{101}{figure.caption.46}
\contentsline {figure}{\numberline {37}{\ignorespaces FleCSI unstructured mesh example from the FleCSALE application.\relax }}{103}{figure.caption.47}
\contentsline {figure}{\numberline {38}{\ignorespaces AMR implementation in MFEM allows many applications to benefit from non-conforming adaptivity, without significant changes in their codes.\relax }}{104}{figure.caption.48}
\contentsline {figure}{\numberline {39}{\ignorespaces New structure of SUNDIALS showing options for the new SUNNONLINEARSOLVER classes.\relax }}{109}{figure.caption.49}
\contentsline {figure}{\numberline {40}{\ignorespaces The libEnsemble control flow showing a manager coordinating workers executing calculations of either simulation functions or generation functions.\relax }}{111}{figure.caption.50}
\contentsline {figure}{\numberline {41}{\ignorespaces STRUMPACK scaling of three phases.\relax }}{113}{figure.caption.51}
\contentsline {figure}{\numberline {42}{\ignorespaces SuperLU triangular solve scaling with 4 matrices.\relax }}{113}{figure.caption.51}
\contentsline {figure}{\numberline {43}{\ignorespaces The proposed Inversion-of-Control approach allowing Fortran applications to define operators on Fortran side while still using ForTrilinos types.\relax }}{115}{figure.caption.52}
\contentsline {figure}{\numberline {44}{\ignorespaces SLATE in the ECP software stack.\relax }}{116}{figure.caption.53}
\contentsline {figure}{\numberline {45}{\ignorespaces An overall 3D FFT-ECP computational pipeline:\nobreakspace {} 1) Need flexible FFT API to take application specific input and output (bricks/pencils/etc., shown on the left and on right);\nobreakspace {} 2) Need efficient packing/unpacking (on a node) and MPI communication routines (shown in the middle);\nobreakspace {} 3) Need efficient 1D (or 2D in some cases) FFTs on the node (shown in the middle).\relax }}{118}{figure.caption.54}
\contentsline {figure}{\numberline {46}{\ignorespaces Runtime of the ILU preconditioner generation on an NVIDIA V100 GPU using the novel ParILU algorithm realized in the PEEKS project and NVIDIA's cuBLAS routine, respectively.\relax }}{121}{figure.caption.55}
\contentsline {figure}{\numberline {47}{\ignorespaces DTK search performance relative to Boost with Intel Xeon E5-2698 and Nvidia P100. 10M points randomly distributed in a unit cube, 1M queries. The time is in seconds. Speedup in bold.\relax }}{124}{figure.caption.56}
\contentsline {figure}{\numberline {48}{\ignorespaces Tasmanian approximation (right) of neutrino capacities (left).\relax }}{124}{figure.caption.57}
\contentsline {figure}{\numberline {49}{\ignorespaces Screen capture of both the Cinema:Newsfeed viewer (left and Cinema:Explorer viewer, showing different views of data from the workflow described above. On the left, the Cinema:Newsfeed viewer shows a graph resulting from the change detection algorithm, and snapshots from the timesteps at the inflection points for the change detection algorithm. This viewer shows a compact `newsfeed' view of the end-to-end analysis. Clicking on the images in this viewer takes the scientist to a more detailed view of the overall set of features captured during the simulation. Because these viewers are implemented in a browser, it is easy to link different viewers together for new tasks and workflows. \relax }}{128}{figure.caption.58}
\contentsline {figure}{\numberline {50}{\ignorespaces (a) FAODEL software stack and (b) a workflow example.\relax }}{132}{figure.caption.59}
\contentsline {figure}{\numberline {51}{\ignorespaces Examples of an \emph {in situ} visualization of a Nalu simulation on 2560 processes of airflow over a wind turbine airfoil. At left: a cross-sectional slice through the airfoil along the direction of flow colored by Q criterion. At right: detail at the leading edge of the wind turbine airfoil. \relax }}{134}{figure.caption.60}
\contentsline {figure}{\numberline {53}{\ignorespaces VeloC results with ECP applications: increase in execution time due to checkpointing (lower is better)\relax }}{136}{figure.caption.62}
\contentsline {subfigure}{\numberline {(a)}{\ignorespaces {HACC}}}{136}{subfigure.53.1}
\contentsline {subfigure}{\numberline {(b)}{\ignorespaces {LatticeQCD}}}{136}{subfigure.53.2}
\contentsline {figure}{\numberline {52}{\ignorespaces VeloC: Architecture\relax }}{136}{figure.caption.61}
\contentsline {figure}{\numberline {54}{\ignorespaces Illustration of data prediction in SZ and visual quality of decompressed data for ECPSky-NYX VX field\relax }}{138}{figure.caption.63}
\contentsline {figure}{\numberline {55}{\ignorespaces Compression Results of Time-based SZ and Random-Access\relax }}{138}{figure.caption.64}
\contentsline {figure}{\numberline {56}{\ignorespaces \textbf {UnifyCR Overview.} Users will be able to give commands in their batch scripts to launch UnifyCR within their allocation. UnifyCR will work with POSIX I/O, common I/O libraries, and VeloC. Once file operations are transparently intercepted by UnifyCR, they will be handled with specialized optimizations to ensure high performance.\relax }}{139}{figure.caption.65}
\contentsline {figure}{\numberline {57}{\ignorespaces \textbf {UnifyCR Design.} The UnifyCR instance consists of a dynamic library and a UnifyCR daemon that runs on each compute node in the job. The library intercepts I/O calls to the UnifyCR mount point from applications, I/O libraries, or VeloC and communicates them to the UnifyCR daemon that handles the I/O operation.\relax }}{140}{figure.caption.66}
\contentsline {figure}{\numberline {58}{\ignorespaces An overview of Virtual Object Layer (VOL)\relax }}{142}{figure.caption.67}
\contentsline {figure}{\numberline {59}{\ignorespaces An example of using ADIOS to support ECP science. This sketch represents the demonstration at the February 2018 ECP Meeting, which featured WDM Fusion, CODAR, ADIOS, and other joint ECP activities. Note that all of the green arrows in the figure represent data communication or storage handled by the ADIOS infrastructure.\relax }}{144}{figure.caption.68}
\contentsline {figure}{\numberline {60}{\ignorespaces The new PnetCDF dispatch layer provides flexibility to target different back-end formats and devices under the PnetCDF API used by many existing applications. \relax }}{146}{figure.caption.69}
\contentsline {figure}{\numberline {61}{\ignorespaces 240:1 {\textsc {zfp}} compressed density field.\relax }}{148}{figure.61}
\contentsline {figure}{\numberline {62}{\ignorespaces ALPINE's strategy for delivering and developing software. We are making use of existing software (ParaView, VisIt), but making sure all new development is shared in all of our tools. The dotted lines represent future work, specifically that the ASCENT API will work with ParaView and VisIt.\relax }}{150}{figure.caption.70}
\contentsline {figure}{\numberline {63}{\ignorespaces In situ visualizations taken from WarpX using VisIt. At left, equally spaced isovalues in an ion accelerator simulation. At right, our method chooses isovalues using topological analysis to more fully represent complex behavior in the data.\relax }}{150}{figure.caption.71}
\contentsline {figure}{\numberline {64}{\ignorespaces Examples of recent progress in VTK-m include (from left to right) multiblock data structures, gradient estimation, and mapping of fields to colors. \relax }}{152}{figure.caption.72}
\contentsline {figure}{\numberline {65}{\ignorespaces The above diagram shows a snippet of the Spack dependency tree including six xSDK member packages. While multiple xSDK member packages depend on OpenMPI, which is an ECP ST software product, OpenMPI is not part of the xSDK\relax }}{155}{figure.caption.73}
\contentsline {figure}{\numberline {66}{\ignorespaces Flang performance is benchmarked against other Fortran compilers. The above diagram shows the relative performance of Flang against PGI Fortran and GNU gfortran\relax }}{165}{figure.caption.74}
