\newlabel{fig:2.3.2.05-ExascaleCodeGenToolkit}
\newlabel{fig:Jacobi_power}
\newlabel{fig:MG}
\newlabel{fig:aries-fadd}
\newlabel{fig:darmaStack}
\newlabel{fig:ecp2}
\newlabel{fig:ecpstleads}
\newlabel{fig:ecpstv1}
\newlabel{fig:expstv2}
\newlabel{fig:ga_bw}
\newlabel{fig:ompix-rma}
\newlabel{fig:parsec}
\newlabel{fig:productsoverview}
\newlabel{fig:project-remapping}
\newlabel{fig:qthreads-finepoints-graph}
\newlabel{fig:rose-raja}
\newlabel{fig:sep18}
\newlabel{fig:slate-parsec}
\newlabel{fig:softwarestack}
\newlabel{fig:sollve-argobots}
\newlabel{fig:sollve-bolt}
\newlabel{fig:sollve-update}
\newlabel{fig:standards}
\newlabel{fig:sympack-perf}
\newlabel{fig:sympack:comm}
\newlabel{fig:sympack:scaling}
\newlabel{fig:task-graph}
\newlabel{fig:tracing-performance}
\newlabel{fig:wbs-transition}
\newlabel{fig:xsdk-diagram}
\newlabel{fig:xsdk-policies}
\newlabel{sect:deliverables}
\newlabel{sect:project-summaries}
\newlabel{sub@fig:sympack:comm}
\newlabel{sub@fig:sympack:scaling}
\newlabel{subsect:ProjectRestructuring}
\newlabel{subsect:products}
\newlabel{subsection:external-contributions}
\newlabel{subsubsect:bolt}
\newlabel{subsubsect:exapapi}
\newlabel{subsubsect:ffts}
\newlabel{subsubsect:llnl-math-libs}
\newlabel{subsubsect:mpich}
\newlabel{subsubsect:openmpi}
\newlabel{subsubsect:sdks}
\newlabel{subsubsect:sollve}
\newlabel{table:eco-products}
\newlabel{table:externalproducts}
\newlabel{table:math-products}
\newlabel{table:pmr-products}
\newlabel{table:sdk-attributes}
\newlabel{table:tools-products}
\newlabel{table:vizdata-products}
\newlabel{table:wbs}
