\contentsline {figure}{\numberline {1}{\ignorespaces The ECP Work Breakdown Structure through Level 3 (L3).\relax }}{3}{figure.caption.2}
\contentsline {figure}{\numberline {2}{\ignorespaces The xSDK is the first SDK for ECP ST, in the Mathematical Libraries technical area\nobreakspace {}\ref {table:wbs}. The xSDK provides the collaboration environment for improving build, install and testing capabilities for member packages such as hypre, PETSc, SuperLU and Trilinos (and other products with green background). Domain components (see orange ovals) are also an important category of the ecosystem, providing leveraged investments for common components in a specific scientific software domain. xSDK capabilities are essential for supporting the multi-physics and multi-scale application requirement that lead to combined use of xSDK libraries. Furthermore, the availability of advanced software platforms such as GitHub, Confluence, JIRA and others enable the level of collaboration needed to create an SDK from independently developed packages.\relax }}{6}{figure.caption.4}
\contentsline {figure}{\numberline {3}{\ignorespaces \textbf {xSDK Community Policies emerged from challenging and passionate discussions about essential values of the math libraries community.} Once established, these community policies represent a living statement of what it means to be part of an SDK, and are used as the criteria for welcoming future members.\relax }}{7}{figure.caption.5}
\contentsline {figure}{\numberline {4}{\ignorespaces \textbf {The ECP ST software stack is delivered to the user community through several channels.} Key channels are via source code, increasing using SDKs, direct to Facilities in collaboration with ECP HI, via binary distributions, in particular the OpenHPC project and via HPC vendors. The SDK leadership team includes ECP ST team members with decades of experience delivering scientific software products.\relax }}{9}{figure.caption.6}
\contentsline {figure}{\numberline {5}{\ignorespaces Project remapping summary from Phase 1 (through November 2017) to Phase 2 (After November 2017)\relax }}{9}{figure.caption.8}
\contentsline {figure}{\numberline {6}{\ignorespaces ECP ST before November 2017 reorganization. This conceptually layout emerged from several years of Exascale planning, conducted primarily within the DOE Office of Advanced Scientific Computing Research (ASCR). After a significant restructuring of ECP that removed much of the facilities activities and reduced the project timeline from 10 to seven years, and a growing awareness of what risks had diminished, this diagram no longer represented ECP ST efforts accurately.\relax }}{11}{figure.caption.9}
\contentsline {figure}{\numberline {7}{\ignorespaces ECP ST after November 2017 reorganization. This diagram more accurately reflects the priorities and efforts of ECP ST given the new ECP project scope and the demands that we foresee.\relax }}{11}{figure.caption.10}
\contentsline {figure}{\numberline {8}{\ignorespaces ECP ST Leadership Team as of November 2017.\relax }}{12}{figure.caption.11}
\contentsline {figure}{\numberline {9}{\ignorespaces {\relax \fontsize {9}{11}\selectfont \abovedisplayskip 8.5\p@ plus3\p@ minus4\p@ \abovedisplayshortskip \z@ plus2\p@ \belowdisplayshortskip 4\p@ plus2\p@ minus2\p@ \def \leftmargin \leftmargini \parsep 4\p@ plus2\p@ minus\p@ \topsep 8\p@ plus2\p@ minus4\p@ \itemsep 4\p@ plus2\p@ minus\p@ {\leftmargin \leftmargini \topsep 4\p@ plus2\p@ minus2\p@ \parsep 2\p@ plus\p@ minus\p@ \itemsep \parsep }\belowdisplayskip \abovedisplayskip {The 54 ECP ST Projects contribute to 89 unique products. ECP ST products are delivered to users via many mechanisms. Provides experience we can leverage across projects. Building via Spack is required for participating in ECP ST releases: 48\% of products already support Spack. 24\% have Spack support in progress. Use of Spack and the ECP ST SDKs will greatly improve builds from source. 81 of 89 packages support users via source builds.}}\relax }}{25}{figure.caption.13}
\contentsline {figure}{\numberline {10}{\ignorespaces ECP ST staff are involved in a variety of official and \textit {de facto} standards committees. Involvement in standards efforts is essential to assuring the sustainability of our products and to assure that emerging Exascale requirements are addressed by these standards.\relax }}{30}{figure.caption.19}
\contentsline {figure}{\numberline {11}{\ignorespaces \textbf {New Legion features such as dynamic tracing significantly improves strong scaling in unstructured mesh computations.}\relax }}{35}{figure.caption.21}
\contentsline {figure}{\numberline {12}{\ignorespaces \textbf {Work by ROSE team shows performance gap analysis for RAJA with different compilers.}\relax }}{37}{figure.caption.22}
\contentsline {figure}{\numberline {13}{\ignorespaces Kokkos Execution and Memory Abstractions\relax }}{38}{figure.caption.23}
\contentsline {figure}{\numberline {14}{\ignorespaces DARMA software stack model showing application-level code implemented with asynchronous programming model (DARMA header library). Application-level semantics are translated into a task graph specification via metaprogramming in the translation layer. Glue code maps task graph specification to individual runtime libraries. Current backend implementations include std::threads, Charm++, MPI + OpenMP, and HPX.\relax }}{41}{figure.caption.24}
\contentsline {figure}{\numberline {15}{\ignorespaces Improved performance of strided get in the 5.7 release series.\relax }}{43}{figure.caption.25}
\contentsline {figure}{\numberline {16}{\ignorespaces MPICH milestones completed in June 2018 and Septmeber 2018\relax }}{47}{figure.caption.26}
\contentsline {figure}{\numberline {17}{\ignorespaces The Legion task graph for a single time step on a single node. The S3D configuration in this example is simulating n-dodecane chemistry reactions in addition to the direct numerical simulation of the turbulent flow.\relax }}{49}{figure.caption.27}
\contentsline {figure}{\numberline {18}{\ignorespaces PaRSEC architecture\relax }}{50}{figure.caption.28}
\contentsline {figure}{\numberline {19}{\ignorespaces PaRSEC architecture \relax }}{51}{figure.caption.29}
\contentsline {figure}{\numberline {20}{\ignorespaces Comparison of put (left) and get (right) RMA performance in a multi-threaded context for Open MPI. Recent OMPI-X contributions are reflected in version 4.0.0a1 (top group of lines), in comparison with v2.1.3.\relax }}{55}{figure.caption.30}
\contentsline {figure}{\numberline {21}{\ignorespaces Non-linear power-performance model in use for MG.C during configuration exploration phase for the runtime system\relax }}{57}{figure.caption.31}
\contentsline {figure}{\numberline {22}{\ignorespaces SOLLVE thrust area updates\relax }}{59}{figure.caption.32}
\contentsline {figure}{\numberline {23}{\ignorespaces Argobots execution model\relax }}{61}{figure.caption.33}
\contentsline {figure}{\numberline {24}{\ignorespaces Pictorial representation of development of BOLT\relax }}{63}{figure.caption.34}
\contentsline {figure}{\numberline {25}{\ignorespaces \textbf {Performance of the symPACK solver using UPC++ V1.0} \relax }}{65}{figure.caption.35}
\contentsline {subfigure}{\numberline {(a)}{\ignorespaces {\textbf {Push} -- MPI two-sided communication\newline \textbf {Pull} -- UPC++: RPC + RMA Get when ready\newline 2 variants with and without event driven scheduling}}}{65}{subfigure.25.1}
\contentsline {subfigure}{\numberline {(b)}{\ignorespaces {Strong scaling of symmetric solvers\newline (Factorization time only)}}}{65}{subfigure.25.2}
\contentsline {figure}{\numberline {26}{\ignorespaces Weak Scaling of 64-bit Unsigned Integer Atomic Hot-Spot Test on ALCF's Theta\relax }}{67}{figure.caption.36}
\contentsline {figure}{\numberline {27}{\ignorespaces This graph shows the performance of Qthreads and OpenMP paired with the FinePoints library for multithreaded MPI. The x-axis varies the buffer sizes transferred in each experiment in the series, and the y-axis shows the network bandwidth achieved. The similar performance of Qthreads and OpenMP justifies use of the former as a suitable proxy for the latter, with the advantage of flexibility for rapid prototyping of new runtime system techniques.\relax }}{69}{figure.caption.37}
\contentsline {figure}{\numberline {28}{\ignorespaces Interface for complex memory that is abstract, portable, extensible to future hardware; including a mechanism-based low-level interface that reins in heterogeneity and an intent-based high-level interface that makes reasonable decisions for applications\relax }}{70}{figure.caption.38}
\contentsline {figure}{\numberline {29}{\ignorespaces Approach to processing user application code with multiple tools to support optimization and correctness checking.\relax }}{80}{figure.caption.39}
\contentsline {figure}{\numberline {30}{\ignorespaces Average power measurements (Watts on y axis) of Jacobi algorithm on a 12,800 x 12,800 grid for different power caps. (A) FLAT mode: data allocated to DDR4; (B) FLAT mode: data allocated to MCDRAM\relax }}{83}{figure.caption.40}
\contentsline {figure}{\numberline {31}{\ignorespaces Y-TUNE Solution Approach.\relax }}{85}{figure.caption.41}
